version: "3"

services:
  wallet:
    container_name: wallet
    env_file: .env
    environment:
      - PORT=${PORT:-8080}
    image: catcatio/wallet
    working_dir: /usr/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      #- ./.env:/usr/app/.env
      #- ./node_modules:/usr/app/node_modules
      - ./src:/usr/app/src
    # command: pm2-runtime start pm2.json --watch
    command: npm run mon
 