version: "3"

services:
  builder:
    container_name: builder
    image: catcatio/builder
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    command: -w
  wallet:
    container_name: wallet
    env_file: .env
    environment:
      - PORT=${PORT:-8080}
    image: catcatio/wallet
    working_dir: /usr/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./.env:/usr/app/.env
      - ./server:/usr/app/server
      - ./pages:/usr/app/pages
      - ./lib:/usr/app/lib
    # command: pm2-runtime start pm2.json --watch
    command: npm run mon
