version: "3"

services:
  wallet:
    container_name: wallet
    env_file: .env
    environment:
      - PORT=${PORT:-8080}
    image: catcatio/wallet
    working_dir: /usr/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./.env:/usr/app/.env
      - ./src:/usr/app/src
    # command: pm2-runtime start pm2.json --watch
    command: npm run mon
    links:
      - mongo
    networks:
      - front
      - back

  mongo_data:  
    image: mongo:3.6
    container_name: mongo_data
    command: bin/true
    networks:
      - back

  mongo:  
    image: mongo:3.6
    container_name: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure
    command: --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - back

networks:
  front:
  back:

volumes:
  mongo_data: